# Jekyll配置文件
# 如果使用Jekyll构建，可以使用此配置文件

# 站点设置
title: 制药过程安全与环保知识库
description: 专业的制药行业安全与环保知识分享平台，涵盖GMP、EPA、OSHA等国际标准
url: "https://your-username.github.io"
baseurl: "/pharma-safety-notes"

# 作者信息
author:
  name: 制药安全专家
  email: contact@pharma-safety.com
  github: your-username

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 排除文件
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# 包含文件
include:
  - _pages

# 集合
collections:
  safety:
    output: true
    permalink: /:collection/:name/
  environment:
    output: true
    permalink: /:collection/:name/
  regulations:
    output: true
    permalink: /:collection/:name/
  case-studies:
    output: true
    permalink: /:collection/:name/
  resources:
    output: true
    permalink: /:collection/:name/

# 默认设置
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "safety"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "environment"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "regulations"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "case-studies"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "page"

# SEO设置
seo:
  type: "WebSite"
  locale: "zh_CN"
  name: "制药过程安全与环保知识库"
  description: "专业的制药行业安全与环保知识分享平台"
  url: "https://your-username.github.io/pharma-safety-notes"
  image: "/assets/images/logo.png"
  twitter:
    card: "summary_large_image"
    site: "@pharma_safety"
  facebook:
    app_id: "your-facebook-app-id"
    publisher: "your-facebook-page-url"

# 社交媒体链接
social:
  github: "your-username"
  twitter: "pharma_safety"
  linkedin: "pharma-safety"
  email: "contact@pharma-safety.com"

# 导航菜单
navigation:
  - title: "首页"
    url: "/"
  - title: "安全知识"
    url: "/safety/"
    children:
      - title: "工艺安全"
        url: "/safety/process-safety/"
      - title: "化学品危害"
        url: "/safety/chemical-hazards/"
      - title: "设备安全"
        url: "/safety/equipment-safety/"
      - title: "个人防护"
        url: "/safety/personal-protection/"
  - title: "环保知识"
    url: "/environment/"
    children:
      - title: "废物管理"
        url: "/environment/waste-management/"
      - title: "排放控制"
        url: "/environment/emissions-control/"
      - title: "绿色化学"
        url: "/environment/green-chemistry/"
      - title: "环保法规"
        url: "/environment/regulations/"
  - title: "法规标准"
    url: "/regulations/"
    children:
      - title: "GMP要求"
        url: "/regulations/gmp-requirements/"
      - title: "EPA法规"
        url: "/regulations/epa-regulations/"
      - title: "OSHA标准"
        url: "/regulations/osha-standards/"
      - title: "国际标准"
        url: "/regulations/international-standards/"
  - title: "案例研究"
    url: "/case-studies/"
    children:
      - title: "事故分析"
        url: "/case-studies/incident-analysis/"
      - title: "最佳实践"
        url: "/case-studies/best-practices/"
      - title: "技术评估"
        url: "/case-studies/technology-reviews/"
  - title: "学习资源"
    url: "/resources/"
    children:
      - title: "术语表"
        url: "/resources/glossary/"
      - title: "参考文献"
        url: "/resources/references/"
      - title: "实用工具"
        url: "/resources/tools-calculators/"

# 搜索设置
search:
  enabled: true
  placeholder: "搜索安全知识、法规标准、案例研究..."
  min_query_length: 2
  max_results: 20

# 分页设置
paginate: 10
paginate_path: "/page:num/"

# 时区
timezone: "Asia/Shanghai"

# 语言设置
lang: "zh-CN"

# 主题设置
theme: "minima"

# 自定义变量
custom_variables:
  version: "1.0.0"
  last_updated: "2024-01-15"
  contributors:
    - "制药安全专家"
    - "环保工程师"
    - "法规专家"
